services:
  web-api:
    build : .
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: password
      SHOW_SQL: true
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  db:
